### PR TITLE
Add 'mv' command

### PR DESCRIPTION
**Pull request by tomplex**
Also aliased with `rename`.

### CODE REVIEW

**Comment by tomplex** [comment]
In order to allow autocompletion of the `rename` & `mv` command, each needs to have a `cmd_*` file in the  `docs/` directory. Unfortunately, this means that they show up in `vb help` as two separate commands. There might be a better way to do this, but I'm not sure if it matters that much.

**Comment by awburgess** [comment]
You could document that one is the alias of the other

**Comment by awburgess** [comment]
Confirming works as expected

```bash
aaron@aaron-VirtualBox ~ $ vb help
Virtualb: A bash-based wrapper for Python's virtualenv.

Usage:

    vb <command> [OPTIONS]

Available commands:

    activate       - Activate the specified virtualenv. 
    deactivate     - Deactivate the currently active environment. 
    freeze         - List the installed packages for a virtualenv. 
    help           - Shows usage information. 
    ls             - List all virtualenvs by name. 
    mv             - Rename a virtualenv. Aliased with 'rename'. 
    new            - Create a new virtualenv. 
    pwd            - Shows the directory of active virtualenv. 
    rename         - Rename a virtualenv. Aliased with 'mv'. 
    rm             - Delete the specified virtualenv. 
    which          - Show the name of the activated virtualenv. 

aaron@aaron-VirtualBox ~ $ vb mv dummy
Must specify virtualenv to rename and the new name.
aaron@aaron-VirtualBox ~ $ vb mv dummy dummy2
aaron@aaron-VirtualBox ~ $ vb ls
dummy2
geo
aaron@aaron-VirtualBox ~ $ vb rename dummy2 yo_momma
aaron@aaron-VirtualBox ~ $ vb ls
geo
yo_momma
aaron@aaron-VirtualBox ~ $ 
```

**Comment by awburgess** [comment]
Reviewed, tested, good to merge

**Pull request merged**
